name: fix

on:
    workflow_dispatch:

jobs:
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: build docker image
              run: docker build fix --file fix/Dockerfile --progress plain
