name: workaround-2

on:
    workflow_dispatch:

jobs:
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: build docker image
              run: docker build workaround-2 --file workaround-2/Dockerfile --progress plain
